logics:
  homepage:
      http:   GET /
      method: App\Logic\AlbumList::all
  login:
      http:   GET /login
      method: App\Logic\UserManager::login
  logout:
      http:   GET /logout
      method: App\Logic\UserManager::logout
  user_auth:
      http:   POST /user/auth
      method: App\Logic\UserManager::auth
  user_edit:
      http:   POST /user/edit
      method: App\Logic\UserManager::edit
  user_ping:
      http:   GET /user/ping
      method: App\Logic\UserManager::ping
  user_report:
      http:   POST /user/report
      method: App\Logic\UserManager::report
  user_feedback:
      http:   POST /user/feedback
      method: App\Logic\UserManager::feedback
  admin_cache:
      http:   GET /admin/cache
      method: App\Logic\UserManager\AdminManager::cache
  admin_cache_clear:
      http:   POST /admin/cache/clear
      method: App\Logic\UserManager\AdminManager::cacheClear
  admin_error:
      http:   GET /admin/error
      method: App\Logic\UserManager\AdminManager::triggerError
  album_create:
      http:   POST /create
      method: App\Logic\AlbumEditor::create
  album_show:
      http:   GET /:y/:m/:d/:album
      method: App\Logic\AlbumList::show
  album_edit:
      http:   POST /:y/:m/:d/:album/edit
      method: App\Logic\AlbumEditor::edit
  album_upload:
      http:   POST /:y/:m/:d/:album/upload
      method: App\Logic\AlbumEditor::upload
  album_download:
      http:   GET /:y/:m/:d/:album/download
      method: App\Logic\AlbumEditor::download
  picture_rotateleft:
      http:   POST /:y/:m/:d/:album/rotateleft
      method: App\Logic\PictureEditor::rotateLeft
  picture_rotateright:
      http:   POST /:y/:m/:d/:album/rotateright
      method: App\Logic\PictureEditor::rotateRight
  albumlist_year:
      http:   GET /:y
      method: App\Logic\AlbumList::year
  albumlist_month:
      http:   GET /:y/:m
      method: App\Logic\AlbumList::month
  albumlist_day:
      http:   GET /:y/:m/:d
      method: App\Logic\AlbumList::day
  cron_lastalbums:
      method: App\Logic\CronTask::lastAlbums

events:
  401: App\Logic\ErrorHandler::accessDenied
  404: App\Logic\ErrorHandler::notFound

errors:
  Exception: App\Logic\ErrorHandler::fatal