logics:
  homepage:
      http:   GET /
      method: Pictobox\Logic\AlbumList::all

  login:
      http:   GET /login
      method: Pictobox\Logic\UserManager::login
  logout:
      http:   GET /logout
      method: Pictobox\Logic\UserManager::logout

  user_auth:
      http:   POST /user/auth
      method: Pictobox\Logic\UserManager::auth
  user_edit:
      http:   POST /user/edit
      method: Pictobox\Logic\UserManager::edit
  user_ping:
      http:   GET /user/ping
      method: Pictobox\Logic\UserManager::ping
  user_report:
      http:   POST /user/report
      method: Pictobox\Logic\UserManager::report
  user_feedback:
      http:   POST /user/feedback
      method: Pictobox\Logic\UserManager::feedback

  admin_cache:
      http:   GET /admin/cache
      method: Pictobox\Logic\UserManager\AdminManager::cache
  admin_cache_clear:
      http:   POST /admin/cache/clear
      method: Pictobox\Logic\UserManager\AdminManager::cacheClear

  album_create:
      http:   POST /create
      method: Pictobox\Logic\AlbumEditor::create
  album_show:
      http:   GET /:y/:m/:d/:album
      method: Pictobox\Logic\AlbumList::show
  album_edit:
      http:   POST /:y/:m/:d/:album/edit
      method: Pictobox\Logic\AlbumEditor::edit
  album_upload:
      http:   POST /:y/:m/:d/:album/upload
      method: Pictobox\Logic\AlbumEditor::upload
  album_download:
      http:   GET /:y/:m/:d/:album/download
      method: Pictobox\Logic\AlbumEditor::download

  picture_rotateleft:
      http:   POST /:y/:m/:d/:album/rotateleft
      method: Pictobox\Logic\PictureEditor::rotateLeft
  picture_rotateright:
      http:   POST /:y/:m/:d/:album/rotateright
      method: Pictobox\Logic\PictureEditor::rotateRight

  albumlist_map:
      http:   GET /map
      method: Pictobox\Logic\AlbumList::map
  albumlist_year:
      http:   GET /:y
      method: Pictobox\Logic\AlbumList::year
  albumlist_month:
      http:   GET /:y/:m
      method: Pictobox\Logic\AlbumList::month
  albumlist_day:
      http:   GET /:y/:m/:d
      method: Pictobox\Logic\AlbumList::day

  error_accessdenied:
      method: Pictobox\Logic\ErrorHandler::accessDenied
  error_notfound:
      method: Pictobox\Logic\ErrorHandler::notFound
  error_maintenance:
      method: Pictobox\Logic\ErrorHandler::maintenance
  error_fatal:
      method: Pictobox\Logic\ErrorHandler::fatal

events:
  401: error_accessdenied
  404: error_notfound
  503: error_maintenance

errors:
  Exception: error_fatal